---
title: "data_prep"
author: "Melissa Gayton"
date: "11/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(readxl)
library(dplyr)
library(tidyverse)
library(knitr)
```

```{r message = FALSE}
# load data
all_data <- read_csv("gov1005_final_app/Data/philly_vars.csv")

```

```{r}
# prep demographic data

# set up variables that will be combos of other variables
demo_data <- all_data %>%
  mutate(IsMentPhysCl = 0, IsMentPhysOp = 0, IsAlcoSubsCl = 0, IsAlcoSubsOp = 0)

# gather mental and physical disabilities into single variable
demo_data$IsMentPhysCl[demo_data$IsMentCl == 1 | demo_data$IsPhysCl == 1] <- 1
demo_data$IsMentPhysOp[demo_data$IsMentOP == 1 | demo_data$IsPhysOP == 1] <- 1
demo_data$IsAlcoSubsCl[demo_data$IsAlcoCl == 1 | demo_data$IsSubsCl == 1] <- 1
demo_data$IsAlcoSubsOp[demo_data$IsAlcoOP == 1 | demo_data$IsSubsOP == 1] <- 1

# make the filing status column easier to work with since this will be column names
demo_data$filingstatus3[demo_data$filingstatus3 == "Spouse filed, client does not want divorce" | demo_data$filingstatus3 == "Spouse filed, client wants divorce"] <- "spouse_filed"
demo_data$filingstatus3[demo_data$filingstatus3 == "Nothing filed, client wants divorce"] <- "none_filed"

# make the house hold language variable 0 or 1
demo_data$LangHH[demo_data$LangHH != "English"] <- 0
demo_data$LangHH[demo_data$LangHH == "English"] <- 1

# gather all the data into variable and value column
demo_data <- demo_data %>%
  select(filingstatus3, legaiddiv, IsInterpCl, Trted, IsFemCl, age, IsBlaCl, IsHisCl, IsWhiCl,
         IsOthAsiCl, LangHH, IsMentPhysCl, IsMentPhysOp,
         IsAlcoSubsCl, IsAlcoSubsOp, IsCrimCl, IsCrimOP) %>%
  gather(key = "var", value = "val", IsFemCl, age, IsBlaCl, IsHisCl, IsWhiCl, IsOthAsiCl, LangHH, IsMentPhysCl, IsMentPhysOp, IsAlcoSubsCl, IsAlcoSubsOp, IsCrimCl, IsCrimOP) %>%
  mutate(val = as.numeric(val)) %>%
  mutate(type = "demo")
```

```{r}
# prep income data

income <- all_data

# making filing status nice for column title
income$filingstatus3[income$filingstatus3 == "Spouse filed, client does not want divorce" | income$filingstatus3 == "Spouse filed, client wants divorce"] <- "spouse_filed"
income$filingstatus3[income$filingstatus3 == "Nothing filed, client wants divorce"] <- "none_filed"

# make medical insurance primary holder variable 0 or 1 
income$MedInsPrimHold[income$MedInsPrimHold == "Client"] <- 1
income$MedInsPrimHold[income$MedInsPrimHold == "Other" | income$MedInsPrimHold == "Opposing Spouse" | income$MedInsPrimHold == ".n"] <- 0

# gather into variable and value column
income <- income %>%
  select(filingstatus3, legaiddiv, IsInterpCl, Trted, IsEmplCl, IsEmplOP, MonthWageCl, AmtMnthIncOP, IsFdStmpCl, IsSSIOrSSDICl, IsTANFCl, IsOthIncCl, IsPensSoleCl, IsPensSoleOP, IsMedInsCl, MedInsPrimHold) %>%
  gather(key = "var", value = "val", IsEmplCl, IsEmplOP, MonthWageCl, AmtMnthIncOP, IsFdStmpCl, IsSSIOrSSDICl, IsTANFCl, IsOthIncCl, IsPensSoleCl, IsPensSoleOP, IsMedInsCl, MedInsPrimHold) %>%
  mutate(val = as.numeric(val)) %>%
  mutate(type = "Income")
```

```{r}
# prep marraige data

marr <- all_data

# make filing status nice
marr$filingstatus3[marr$filingstatus3 == "Spouse filed, client does not want divorce" | marr$filingstatus3 == "Spouse filed, client wants divorce"] <- "spouse_filed"
marr$filingstatus3[marr$filingstatus3 == "Nothing filed, client wants divorce"] <- "none_filed"

# gather marriage vars into variable and value column
marr <- marr %>%
  select(filingstatus3, legaiddiv, IsInterpCl, Trted, lengthmar, IsOPInClHm, prevdiv, IsBenSpSupPhCnty, IsClWntSpSup, IsOPEconCla, IsPFAAgstCl, IsPFAProtCl, IsPFAAgstOP, IsGrndDiv2Yr, IsGrndDivMutCon, IsGrndDivDese, IsGrnDivInd, IsGrnDivOth) %>%
  gather(key = "var", value = "val", lengthmar, IsOPInClHm, prevdiv, IsBenSpSupPhCnty, IsClWntSpSup, IsOPEconCla, IsPFAAgstCl, IsPFAProtCl, IsPFAAgstOP, IsGrndDiv2Yr, IsGrndDivMutCon, IsGrndDivDese, IsGrnDivInd, IsGrnDivOth) %>%
  mutate(val = as.numeric(val)) %>%
  mutate(type = "Marr")
```

```{r}
# prep fam data

fam <- all_data

# make filing status nice
fam$filingstatus3[fam$filingstatus3 == "Spouse filed, client does not want divorce" | fam$filingstatus3 == "Spouse filed, client wants divorce"] <- "spouse_filed"
fam$filingstatus3[fam$filingstatus3 == "Nothing filed, client wants divorce"] <- "none_filed"

# gather family vars into variable and value column
fam <- fam %>%
  select(filingstatus3, legaiddiv, IsInterpCl, Trted, num_chld, chldmar, chldmar18, chldmar18cust, chldmar18supp) %>%
  gather(key = "var", value = "val", num_chld, chldmar, chldmar18, chldmar18cust, chldmar18supp) %>%
  mutate(val = as.numeric(val)) %>%
  mutate(type = "fam")
```

```{r}
# prep asset data
asset <- all_data %>%
  mutate(ClOwnREH = 0, OwnREH = 0, DesREH = 0, OwnAuto = 0, ClOwnAuto = 0, DesAuto = 0, OwnPenAnn = 0, DesPenAnn = 0, OwnBkAcct = 0, OwnBus = 0, OwnCC = 0, OwnLoan = 0)

# make filing status pretty

asset$filingstatus3[asset$filingstatus3 == "Spouse filed, client does not want divorce" | asset$filingstatus3 == "Spouse filed, client wants divorce"] <- "spouse_filed"
asset$filingstatus3[asset$filingstatus3 == "Nothing filed, client wants divorce"] <- "none_filed"

# client has sole or joint ownership of REH

asset$ClOwnREH[asset$OwnREH1 == "Joint" | asset$OwnREH1 == "Client alone" | asset$OwnREH2 == "Joint" | asset$OwnREH2 == "Client alone" | asset$OwnREH3 == "Joint" | asset$OwnREH3 == "Client alone" | asset$OwnREHOth == "Joint" | asset$OwnREHOth == "Client alone"] <- 1

# client or spouse has REH

asset$OwnREH[asset$IsREH1 == 1] <- 1

# Cl or spouse own auto
asset$OwnAuto[asset$IsAuto1 == 1] <- 1

# cl has sole or joint own of auto

asset$ClOwnAuto[asset$OwnAuto1 == "Joint" | asset$OwnAuto1 == "Client alone" | asset$OwnAuto2 == "Joint" | asset$OwnAuto2 == "Client alone" | asset$OwnAuto3 == "Joint" | asset$OwnAuto3 == "Client alone"] <- 1

# client or spouse has pension/annuity

asset$OwnPenAnn[asset$IsPenAnn1 == 1] <- 1

# client or spouse has bank account

asset$OwnBkAcct[asset$IsBkAcct1 == 1] <- 1

# client or spouse has business

asset$OwnBus[asset$num_Bus != 0] <- 1

# client or spouse has credit card
asset$OwnCC[asset$num_CC != 0] <- 1

# client or spouse has loan

asset$OwnLoan[asset$num_Loan != 0] <- 1

# gather asset data into variable and value columns
asset <- asset %>%
  select(filingstatus3, legaiddiv, IsInterpCl, Trted, clownasset, OwnREH, num_REH, ClOwnREH, desshareREH, OwnAuto,num_Auto, ClOwnAuto, desshareAuto, OwnPenAnn, num_PenAnn, clownPenAnn, dessharePenAnn, OwnBkAcct, num_BkAcct, clownBkAcct, desshareBkAcct, OwnBus, num_Bus, clownBus, desshareBus, OwnCC, num_CC, clownCC, desOPCC, OwnLoan, num_Loan, clownLoan, desOPLoan) %>%
  gather(key = "var", value = "val", clownasset, OwnREH, num_REH, ClOwnREH, desshareREH, OwnAuto, num_Auto, ClOwnAuto, desshareAuto, OwnPenAnn, num_PenAnn, clownPenAnn, dessharePenAnn, OwnBkAcct, num_BkAcct, clownBkAcct, desshareBkAcct, OwnBus, num_Bus, clownBus, desshareBus, OwnCC, num_CC, clownCC, desOPCC, OwnLoan, num_Loan, clownLoan, desOPLoan) %>%
  mutate(val = as.numeric(val)) %>%
  mutate(type = "Asset")

# make asset variables pretty for table
asset$var[asset$var == "clownasset"] <- "Client has sole or joint ownership of any asset"
asset$var[asset$var == "OwnREH"] <- "Client or Spouse has real estate/home"
asset$var[asset$var == "num_REH"] <- "Number of real estate holdings/houses owned by Client or Spouse"
asset$var[asset$var == "ClOwnREH"] <- "Client has sole or joint ownership of real estate/house"
asset$var[asset$var == "desshareREH"] <- "Client wants sole/partial ownership of real estate/house"
asset$var[asset$var == "OwnAuto"] <- "Client or Spouse has automobile"
asset$var[asset$var == "num_Auto"] <- "Number of automobiles owned by Client or Spouse"
asset$var[asset$var == "ClOwnAuto"] <- "Client has sole or joint ownership of automobile"
asset$var[asset$var == "desshareAuto"] <- "Client wants sole/partial ownership of automobile"
asset$var[asset$var == "OwnPenAnn"] <- "Client or Spouse has pension/annuity"
asset$var[asset$var == "num_PenAnn"] <- "Number of pensions/annuities owned by Client or Spouse"
asset$var[asset$var == "clownPenAnn"] <- "Client has sole or joint ownership of pension/annuity"
asset$var[asset$var == "dessharePenAnn"] <- "Client wants sole/partial ownership of pension/annuity"
asset$var[asset$var == "OwnBkAcct"] <- "Client or Spouse has bank account"
asset$var[asset$var == "num_BkAcct"] <- "Number of bank accounts owned by Client or Spouse"
asset$var[asset$var == "clownBkAcct"] <- "Client has sole or joint ownership of bank account"
asset$var[asset$var == "desshareBkAcct"] <- "Client wants sole/partial ownership of bank account"
asset$var[asset$var == "OwnBus"] <- "Client or Spouse has business"
asset$var[asset$var == "num_Bus"] <- "Number of businesses owned by Client or Spouse"
asset$var[asset$var == "clownBus"] <- "Client has sole or joint ownership of business"
asset$var[asset$var == "desshareBus"] <- "Client wants sole/partial ownership of business"
asset$var[asset$var == "OwnCC"] <- "Client or Spouse has credit card"
asset$var[asset$var == "num_CC"] <- "Number of credit cards owned by Client or Spouse"
asset$var[asset$var == "clownCC"] <- "Client has sole or joint ownership of credit card"
asset$var[asset$var == "desOPCC"] <- "Client wants spouse to own credit card debt"
asset$var[asset$var == "OwnLoan"] <- "Client or Spouse has loan"
asset$var[asset$var == "num_Loan"] <- "Number of loans owned by Client or Spouse"
asset$var[asset$var == "clownLoan"] <- "Client has sole or joint ownership of loan"
asset$var[asset$var == "desOPLoan"] <- "Client wants spouse to own loan debt"

# create separate table for asset tab
asset_tab <- asset

# combine the demo, income, marriage, family, and asset tables

table_data <- asset %>%
  merge(income, all = TRUE) %>%
  merge(demo_data, all = TRUE) %>%
  merge(marr, all = TRUE) %>%
  merge(fam, all = TRUE) %>%
  # set up different columsn for pvalues
  mutate(filing_p_val = 0, legaiddiv_p_val = 0, interp_p_val = 0, trted_p_val = 0)

var_names <- unique(table_data$var)

# calculate p values comparing across filing status

i <- 1

for(i in 1:length(var_names)) {
  table_data$filing_p_val[table_data$var == var_names[i]] <- t.test(table_data$val[table_data$var == var_names[i]] ~ table_data$filingstatus3[table_data$var == var_names[i]], conf.level = 0.95)$p.value
}

# calculate p values comparing across legal aid division status

i <- 1

for(i in 1:length(var_names)) {
  table_data$legaiddiv_p_val[table_data$var == var_names[i]] <- t.test(table_data$val[table_data$var == var_names[i]] ~ table_data$legaiddiv[table_data$var == var_names[i]], conf.level = 0.95)$p.value
}

# calculate p values comparing across interpreter or not

for(i in 1:length(var_names)) {
  table_data$interp_p_val[table_data$var == var_names[i]] <- t.test(table_data$val[table_data$var == var_names[i]] ~ table_data$IsInterpCl[table_data$var == var_names[i]], conf.level = 0.95)$p.value
}

# calculate p values for comparing across treatment groups

for(i in 1:length(var_names)) {
  table_data$trted_p_val[table_data$var == var_names[i]] <- t.test(table_data$val[table_data$var == var_names[i]] ~ table_data$Trted[table_data$var == var_names[i]], conf.level = 0.95)$p.value
}

# prepare table with means, mean difference, and p value across filing status, legal aid division, and interpreter. I already did it with just filing data when i decided to do the other ones too and i figured it was easier to just copy the code and change the variables and then combine than to try to change the code to do all of the comparisons at once

filing_data <-table_data %>%
  group_by(filingstatus3, var, filing_p_val, type) %>%
  summarise(mean = mean(val, na.rm = TRUE), sd = sd(val, na.rm = TRUE)) %>%
  unite(mean_sd, mean, sd) %>%
  spread(filingstatus3, mean_sd) %>%
  separate(none_filed, into = c("nf_mean", "nf_sd"), sep = "_") %>%
  separate(spouse_filed, into = c("s_mean", "s_sd"), sep = "_") %>%
  group_by(var) %>%
  mutate(nf_mean = as.numeric(nf_mean), s_mean = as.numeric(s_mean), nf_sd = as.numeric(nf_sd), s_sd = as.numeric(s_sd), mean_diff_filing = s_mean - nf_mean) %>%
  unite(none_filed, nf_mean, nf_sd) %>%
  unite(spouse_filed, s_mean, s_sd) %>%
  gather(key = "filing_status", "value" = mean_sd, none_filed, spouse_filed) %>%
  separate(mean_sd, c("mean", "sd"), sep = "_") %>%
  select(var, filing_status, mean, mean_diff_filing, filing_p_val, type) %>%
  spread(filing_status, mean) %>%
  select(var, none_filed, spouse_filed, mean_diff_filing, filing_p_val) %>%
  ungroup()

legaiddiv_data <- table_data
  
legaiddiv_data$legaiddiv[legaiddiv_data$legaiddiv == "Post-cessation"] <- "post"
legaiddiv_data$legaiddiv[legaiddiv_data$legaiddiv == "Pre-cessation"] <- "pre"

legaiddiv_data <- legaiddiv_data %>%
  group_by(legaiddiv, var, legaiddiv_p_val, type) %>%
  summarise(mean = mean(val, na.rm = TRUE), sd = sd(val, na.rm = TRUE)) %>%
  unite(mean_sd, mean, sd) %>%
  spread(legaiddiv, mean_sd) %>%
  separate(post, into = c("post_mean", "post_sd"), sep = "_") %>%
  separate(pre, into = c("pre_mean", "pre_sd"), sep = "_") %>%
  group_by(var) %>%
  mutate(post_mean = as.numeric(post_mean), pre_mean = as.numeric(pre_mean), post_sd = as.numeric(post_sd), pre_sd = as.numeric(pre_sd), mean_diff_legaiddiv = post_mean - pre_mean) %>%
  unite(post, post_mean, post_sd) %>%
  unite(pre, pre_mean, pre_sd) %>%
  gather(key = "legaiddiv", "value" = mean_sd, pre, post) %>%
  separate(mean_sd, c("mean", "sd"), sep = "_") %>%
  select(var, legaiddiv, mean, mean_diff_legaiddiv, legaiddiv_p_val, type) %>%
  spread(legaiddiv, mean) %>%
  select(var, pre, post, mean_diff_legaiddiv, legaiddiv_p_val) %>%
  ungroup()

interp_data <- table_data

interp_data$IsInterpCl[interp_data$IsInterpCl == "1"] <- "yes_interp"
interp_data$IsInterpCl[interp_data$IsInterpCl == "0"] <- "no_interp"

interp_data <- interp_data %>%
  group_by(IsInterpCl, var, interp_p_val, type) %>%
  summarise(mean = mean(val, na.rm = TRUE), sd = sd(val, na.rm = TRUE)) %>%
  unite(mean_sd, mean, sd) %>%
  spread(IsInterpCl, mean_sd) %>%
  separate(yes_interp, into = c("yes_mean", "yes_sd"), sep = "_") %>%
  separate(no_interp, into = c("no_mean", "no_sd"), sep = "_") %>%
  group_by(var) %>%
  mutate(yes_mean = as.numeric(yes_mean), no_mean = as.numeric(no_mean), yes_sd = as.numeric(yes_sd), no_sd = as.numeric(no_sd), mean_diff_interp = yes_mean - no_mean) %>%
  unite(yes_interp, yes_mean, yes_sd) %>%
  unite(no_interp, no_mean, no_sd) %>%
  gather(key = "interp", "value" = mean_sd, yes_interp, no_interp) %>%
  separate(mean_sd, c("mean", "sd"), sep = "_") %>%
  select(var, interp, mean, mean_diff_interp, interp_p_val, type) %>%
  spread(interp, mean) %>%
  select(var, no_interp, yes_interp, mean_diff_interp, interp_p_val, type) %>%
  ungroup()

treatment <- table_data

treatment$Trted[treatment$Trted == "1"] <- "yes_trted"
treatment$Trted[treatment$Trted == "0"] <- "no_trted"

treatment <- treatment %>%
  group_by(Trted, var, trted_p_val, type) %>%
  summarise(mean = mean(val, na.rm = TRUE), sd = sd(val, na.rm = TRUE)) %>%
  unite(mean_sd, mean, sd) %>%
  spread(Trted, mean_sd) %>%
  separate(yes_trted, into = c("yes_mean", "yes_sd"), sep = "_") %>%
  separate(no_trted, into = c("no_mean", "no_sd"), sep = "_") %>%
  group_by(var) %>%
  mutate(yes_mean = as.numeric(yes_mean), no_mean = as.numeric(no_mean), yes_sd = as.numeric(yes_sd), no_sd = as.numeric(no_sd), mean_diff_trted = yes_mean - no_mean) %>%
  unite(yes_trted, yes_mean, yes_sd) %>%
  unite(no_trted, no_mean, no_sd) %>%
  gather(key = "Trted", "value" = mean_sd, yes_trted, no_trted) %>%
  separate(mean_sd, c("mean", "sd"), sep = "_") %>%
  select(var, Trted, mean, mean_diff_trted, trted_p_val, type) %>%
  spread(Trted, mean) %>%
  select(var, no_trted, yes_trted, mean_diff_trted, trted_p_val, type) %>%
  ungroup()

table_data <- filing_data %>%
  merge(legaiddiv_data, all = TRUE) %>%
  merge(interp_data, all = TRUE) %>%
  merge(treatment, all = TRUE)

```

```{r}

# make variables nice for table, because this is what's getting presented. probably there's a prettier way how to do this, but i just went ahead and hard coded all the changes in because eh it works

table_data$var[table_data$var == "IsFemCl"] <- "Female"
table_data$var[table_data$var == "age"] <- "Age"
table_data$var[table_data$var == "IsBlaCl"] <- "Black/African-American"
table_data$var[table_data$var == "IsHisCl"] <- "Hispanic/Latino/of Spanish origin"
table_data$var[table_data$var == "IsWhiCl"] <- "White/Caucasian"
table_data$var[table_data$var == "IsOthAsiCl"] <- "Other Race"
table_data$var[table_data$var == "LangHH"] <- "English primarily spoken in marital home"
table_data$var[table_data$var == "IsMentPhysCl"] <- "Client has history of mental or physical disability"
table_data$var[table_data$var == "IsMentPhysOp"] <- "Spouse has history of mental or physical disability"
table_data$var[table_data$var == "IsAlcoSubsCl"] <- "Client has history of alcohol or substance abuse"
table_data$var[table_data$var == "IsAlcoSubsOp"] <- "Spouse has history of alcohol or substance abuse"
table_data$var[table_data$var == "IsCrimCl"] <- "Client has criminal record"
table_data$var[table_data$var == "IsCrimOP"] <- "Spouse has criminal record"

# make income variables pretty for table
table_data$var[table_data$var == "IsEmplCl"] <- "Client Employed"
table_data$var[table_data$var == "IsEmplOP"] <- "Spouse employed"
table_data$var[table_data$var == "MonthWageCl"] <- "Client's monthly employment income"
table_data$var[table_data$var == "AmtMnthIncOP"] <- "Spouse's monthly employment income"
table_data$var[table_data$var == "IsFdStmpCl"] <- "Food stamps"
table_data$var[table_data$var == "IsSSIOrSSDICl"] <- "SSI or SSDI"
table_data$var[table_data$var == "IsTANFCl"] <- "TANF or other welfare"
table_data$var[table_data$var == "IsOthIncCl"] <- "Other income"
table_data$var[table_data$var == "IsPensSoleCl"] <- "Client has pension solely in his/her name"
table_data$var[table_data$var == "IsPensSoleOP"] <- "Spouse has pension solely in his/her name"
table_data$var[table_data$var == "IsMedInsCl"] <- "Client has health insurance"
table_data$var[table_data$var == "MedInsPrimHold"] <- "Client is policyholder of client's health insurance"

# make marriage variables pretty for table
table_data$var[table_data$var == "lengthmar"] <- "Years of marriage"
table_data$var[table_data$var == "IsOPInClHm"] <- "Spouse currently lives in client's home"
table_data$var[table_data$var == "prevdiv"] <- "Client is previously divorced"
table_data$var[table_data$var == "IsBenSpSupPhCnty"] <- "Client is current beneficiary of spousal support order"
table_data$var[table_data$var == "IsClWntSpSup"] <- "Client wants spousal support"
table_data$var[table_data$var == "IsOPEconCla"] <- "Spouse is making economic claims"
table_data$var[table_data$var == "IsPFAAgstCl"] <- "Client has had PFA order entered against him/her"
table_data$var[table_data$var == "IsPFAProtCl"] <- "Client has had PFA order entered protecting him/her"
table_data$var[table_data$var == "IsPFAAgstOP"] <- "Spouse has had PFA order entered against him/her"
table_data$var[table_data$var == "IsGrndDiv2Yr"] <- "Grounds for divorce: 2-year separation"
table_data$var[table_data$var == "IsGrndDivMutCon"] <- "Grounds for divorce: mutual consent"
table_data$var[table_data$var == "IsGrndDivDese"] <- "Grounds for divorce: desertion"
table_data$var[table_data$var == "IsGrnDivInd"] <- "Grounds for divorce: indignities"
table_data$var[table_data$var == "IsGrnDivOth"] <- "Grounds for divorce: other"

# make fam vars pretty
table_data$var[table_data$var == "num_chld"] <- "Number of children of either spouse"
table_data$var[table_data$var == "chldmar"] <- "Client has child of marriage"
table_data$var[table_data$var == "chldmar18"] <- "Client has child of marriage under 18"
table_data$var[table_data$var == "chldmar18cust"] <- "Client desires custody over child of marriage under 18"
table_data$var[table_data$var == "chldmar18supp"] <- "Client desires child support for child of marriage under 18"


table_data <- table_data %>%
  mutate(var = as.factor(var)) %>%
  mutate(var = fct_relevel(var, c("Female", "Age", "Black/African-American", "Hispanic/Latino/of Spanish origin", "White/Caucasian", "Other Race", "English primarily spoken in marital home", "Client has history of mental or physical disability", "Spouse has history of mental or physical disability","Client has history of alcohol or substance abuse", "Spouse has history of alcohol or substance abuse", "Client has criminal record", "Spouse has criminal record", "Client Employed", "Spouse employed", "Client's monthly employment income", "Spouse's monthly employment income", "Food stamps", "SSI or SSDI", "TANF or other welfare", "Other income", "Client has pension solely in his/her name", "Spouse has pension solely in his/her name", "Client has health insurance", "Client is policyholder of client's health insurance", "Client has sole or joint ownership of any asset", "Client or Spouse has real estate/home", "Number of real estate holdings/houses owned by Client or Spouse", "Client has sole or joint ownership of real estate/house", "Client wants sole/partial ownership of real estate/house", "Client or Spouse has automobile","Number of automobiles owned by Client or Spouse", "Client has sole or joint ownership of automobile", "Client wants sole/partial ownership of automobile", "Client or Spouse has pension/annuity", "Number of pensions/annuities owned by Client or Spouse", "Client has sole or joint ownership of pension/annuity", "Client wants sole/partial ownership of pension/annuity", "Client or Spouse has bank account", "Number of bank accounts owned by Client or Spouse", "Client has sole or joint ownership of bank account", "Client wants sole/partial ownership of bank account", "Client or Spouse has business", "Number of businesses owned by Client or Spouse", "Client has sole or joint ownership of business", "Client wants sole/partial ownership of business", "Client or Spouse has credit card", "Number of credit cards owned by Client or Spouse", "Client has sole or joint ownership of credit card", "Client wants spouse to own credit card debt", "Client or Spouse has loan", "Number of loans owned by Client or Spouse", "Client has sole or joint ownership of loan", "Client wants spouse to own loan debt", "Years of marriage", "Spouse currently lives in client's home", "Client is previously divorced", "Client is current beneficiary of spousal support order", "Client wants spousal support", "Spouse is making economic claims", "Client has had PFA order entered against him/her", "Client has had PFA order entered protecting him/her", "Spouse has had PFA order entered against him/her", "Grounds for divorce: 2-year separation", "Grounds for divorce: mutual consent", "Grounds for divorce: desertion", "Grounds for divorce: indignities", "Grounds for divorce: other", "Number of children of either spouse", "Client has child of marriage", "Client has child of marriage under 18", "Client desires custody over child of marriage under 18", "Client desires child support for child of marriage under 18"))) %>%
  arrange(var) %>%
  # make sure the data is numeric
  mutate(none_filed = as.numeric(none_filed), spouse_filed = as.numeric(spouse_filed), yes_interp = as.numeric(yes_interp), no_interp = as.numeric(no_interp), post = as.numeric(post), pre = as.numeric(pre), yes_trted = as.numeric(yes_trted), no_trted = as.numeric(no_trted))
```

```{r}
# turn the data into long format for the plot

plot_data <- table_data %>%
  select(var, filing_p_val, legaiddiv_p_val, interp_p_val, trted_p_val) %>%
  gather("key", "value", filing_p_val, legaiddiv_p_val, interp_p_val, trted_p_val)
```

```{r}
# prepare mini table with just stuff about wages
wage_data <- all_data %>%
  filter(!is.na(MonthWageCl), MonthWageCl != 0, !is.na(AmtMnthIncOP), AmtMnthIncOP != 0, AmtMnthIncOP <= 15000) 

# figure out how many clients are unemployed
number_zero_cl <- all_data %>%
  select(RefNum, MonthWageCl) %>%
  filter(MonthWageCl == 0) %>%
  count(MonthWageCl)

# figure out how many opposition are unemployed
number_zero_op <- all_data %>%
  select(RefNum, AmtMnthIncOP) %>%
  filter(AmtMnthIncOP == 0) %>%
  count(AmtMnthIncOP)

# mini table with just length of marriage
marr_data <- all_data %>%
  select(lengthmar) %>%
  filter(! is.na(lengthmar))
  
# get a table with percentages of races
race_data <- all_data %>%
  # subtracting 2 from white clients due to 2 people marking both white and hispanic - counting white hispanics as just hispanic
  summarize(Black = sum((IsBlaCl)), White = (sum(IsWhiCl) - 2), Hispanic = sum(IsHisCl), Asian = sum(IsAsiCl), Other = sum(IsOthCl)) %>%
  # gather it
  gather(key = "race", "value" = n, Black, White, Hispanic, Asian, Other) %>%
  # make into percent
  select(race, n) %>%
  mutate(race = fct_relevel(race, c("Black", "Hispanic", "White", "Asian", "Other")))

total = sum(race_data$n)

pct_blck = paste0(round((race_data$n[race_data$race == "Black"] / total) * 100, digits = 2), "%")


# get all the clients who are getting benefits and sum
ben_data <- all_data %>%
  filter(IsBenSpSupCl == 1 | IsTANFCl == 1 | IsSSIOrSSDICl == 1 | IsSSCl == 1 | IsOthRetCl == 1 | IsUnempCl == 1 | IsFdStmpCl == 1 | IsOthIncCl == 1) %>%
  summarize(n = n())

# get all the data on domestic abuse
dom_abuse <- all_data %>%
  select(IsPFAAgstCl, DatePFAAgstCl, IsPFAAgstClPhCnty, IsPFAAgstClStillEff, IsPFAProtCl, DatePFAProtCl, IsPFAProtClPhCnty, IsPFAProtClStillEff, IsPFAAgstOP)

# get data for child bar graph

child_data <- all_data %>%
  select(num_chld) %>%
  mutate(num_chld = as.factor(num_chld)) %>%
  summarise("zero" = sum(num_chld == "0"), "one" = sum(num_chld == "1"), "two" = sum(num_chld == "2"), "three" = sum(num_chld == "3"), "four" = sum(num_chld == "4"), "five" = sum(num_chld == "5")) %>%
  gather(key = "num", val = "total", zero, one, two , three, four, five)

# percent w no children
none = paste0(round((child_data$total[child_data$num == "zero"]/sum(child_data$total)) * 100, digits = 2), "%")

# create separate table for asset tab
asset_tab <- asset_tab %>%
  select(var, val) %>%
  filter(!grepl("Number",var)) %>%
  group_by(var) %>%
  summarise(n = sum(val)) %>%
  mutate(var = as.factor(var)) %>%
  mutate(var = fct_relevel(var, c("Client has sole or joint ownership of any asset", "Client or Spouse has real estate/home", "Client has sole or joint ownership of real estate/house", "Client wants sole/partial ownership of real estate/house", "Client or Spouse has automobile", "Client has sole or joint ownership of automobile", "Client wants sole/partial ownership of automobile", "Client or Spouse has pension/annuity", "Client has sole or joint ownership of pension/annuity", "Client wants sole/partial ownership of pension/annuity", "Client or Spouse has bank account", "Client has sole or joint ownership of bank account", "Client wants sole/partial ownership of bank account", "Client or Spouse has business", "Client has sole or joint ownership of business", "Client wants sole/partial ownership of business", "Client or Spouse has credit card", "Client has sole or joint ownership of credit card", "Client wants spouse to own credit card debt", "Client or Spouse has loan", "Client has sole or joint ownership of loan", "Client wants spouse to own loan debt"))) %>%
  arrange(desc(var)) %>%
  mutate(group = "", type = "")
  
asset_tab$group[grepl("real estate", asset_tab$var)] <- "Real Estate"
asset_tab$group[grepl("automobile", asset_tab$var)] <- "Automobile"
asset_tab$group[grepl("pension/annuity", asset_tab$var)] <- "Pension/Annuity"
asset_tab$group[grepl("bank", asset_tab$var)] <- "Bank Account"
asset_tab$group[grepl("business", asset_tab$var)] <- "Business"
asset_tab$group[grepl("credit card", asset_tab$var)] <- "Credit Card"
asset_tab$group[grepl("loan", asset_tab$var)] <- "Loan"

asset_tab$type[grepl("has sole or joint", asset_tab$var)] <- "Client has sole or joint ownership"
asset_tab$type[grepl("Client or Spouse", asset_tab$var)] <- "Client or Spouse owns"
asset_tab$type[grepl("Client wants", asset_tab$var)] <- "Client wants asset/wants Spouse to own debt"
```

